# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'     
        required: true
        type: string

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build Release
      run: dotnet publish MPSLInterpreter --os win
    - name: Rename Executable
      run: mv MPSLInterpreter/bin/Release/net9.0/win-x64/publish/MPSLInterpreter.exe MPSLInterpreter/bin/Release/net9.0/win-x64/publish/mpsl.exe
    - name: Upload to Release Action
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: Release v${{ inputs.version }}
        path: MPSLInterpreter/bin/Release/net9.0/win-x64/publish/mpsl.exe
        repo-token: ${{ secrets.GITHUB_TOKEN }}
